# Name of your application. Used to uniquely configure containers.
service: kucharka

# Name of the container image.
image: janpeterka/kucharka

# Deploy to these servers.
servers:
  - navarit

volumes:
  - "/root/storage:/rails/storage"

# networks: This is not supported now (24.6.2024)
  # - kucharka-network

# Credentials for your image host.
registry:
  server: ghcr.io
  username: janpeterka

  # Always use an access token rather than real password when possible.
  password:
    - KAMAL_REGISTRY_TOKEN

# Inject ENV variables into containers (secrets come from .env).
# Remember to run `kamal env push` after making changes!
env:
#   clear:
#     DB_HOST: 192.168.0.2
  secret:
    - RAILS_MASTER_KEY
    - MYSQL_ROOT_PASSWORD
    - MYSQL_PASSWORD

# Use a different ssh user than root
# ssh:
#   user: app

# Configure builder setup.
builder:
  arch: amd64
  # multiarch: false
#   args:
#     RUBY_VERSION: 3.2.0
#   secrets:
#     - GITHUB_TOKEN
#   remote:
#     arch: amd64
#     host: ssh://app@192.168.0.1

# Use accessory services (secrets come from .env).
accessories:
  db:
    image: mysql
    host: kucharka
    port: 3306
    # TODO: dont tunnel port
    # port: 127.0.0.1:3306:3306

    env:
      clear:
        MYSQL_ROOT_HOST: '%'
        MYSQL_DATABASE: kucharka
        MYSQL_USER: kucharka
      secret:
        - MYSQL_ROOT_PASSWORD
        - MYSQL_PASSWORD

    # files:
      # - config/mysql/production.cnf:/etc/mysql/my.cnf
      # - db/production.sql:/docker-entrypoint-initdb.d/setup.sql
    directories:
      - data:/var/lib/mysql

proxy:
  app_port: 3000
