name: github-actions-rails-mysql

on:
  pull_request:
    branches: ['*']
  push:
    branches: [master]
jobs:
  test:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.1
        env:
        #   MYSQL_HOST: 127.0.0.1
          MYSQL_DB: kucharka_test
          MYSQL_USER: kucharka
          MYSQL_PASSWORD: kucharka
          MYSQL_ROOT_PASSWORD: kucharka
        ports:
          - "3306:3306"
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - uses: actions/checkout@v2
      - name: Setup Ruby 3.2.2
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2.2
          bundler: default
          bundler-cache: true
    
      - name: Run tests
        env:
          RAILS_ENV: test
          DATABASE_PORT: 3306
        run: |
          bin/rails db:create
          bin/rails db:schema:load
          bin/rails test