# This workflow uses actions that are not certified by GitHub.  They are
# provided by a third-party and are governed by separate terms of service,
# privacy policy, and support documentation.
#
# This workflow will install a prebuilt Ruby version, install dependencies, and
# run tests and linters.
name: "Ruby on Rails CI"
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  test:
    runs-on: ubuntu-latest
    services:
      mariadb:
        image: mariadb:10.5
        ports:
          - "3306:3306"
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: rails_test
          MYSQL_USER: rails
          MYSQL_PASSWORD: password
    env:
      RAILS_ENV: test
      DATABASE_URL: "trilogy://rails:password@localhost:3306/rails_test"
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      # Add or replace dependency steps here
      - name: Install Ruby and gems
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      # Add or replace database setup steps here
      - name: Set up database schema
        run: bin/rails db:schema:load
      # Add or replace test runners here
      - name: Run tests
        run: bin/rake

  lint:
    env:
      RAILS_ENV: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install Ruby and gems
        uses: ruby/setup-ruby@v1 # v1.146.0
        with:
          bundler-cache: true
      # Add or replace any other lints here
      # - name: Security audit dependencies
        # run: bundler-audit --update
      # - name: Security audit application code
      #   run: brakeman -q -w2
      # - name: Lint Ruby files
      #   run: rubocop --parallel
      - name: Check rails best practices
        run: rails_best_practices 
      
